Repository astral-sh/rye, pull requests merged in 2024-04, with the labels that each got.

#987 DOC: correct black run command and refine text
  docs/guide/basics.md
Labels: documentation

#1001 doc: Typos and wording
  docs/guide/config.md
Labels: documentation

#986 DOC: simplify wording for rye sync after rye add
  docs/guide/basics.md
Labels: documentation

#1038 Allow comments in `.python-version`
  rye/src/platform.rs
Labels: bug

#1030 Add nushell completion support
  Cargo.lock
  docs/guide/commands/self/completion.md
  docs/guide/installation.md
  rye/Cargo.toml
  rye/src/cli/rye.rs
Labels: enhancement

#1054 Fix Rye not using user-chosen toolchain as default during installation
  rye/src/cli/rye.rs
Labels: bug
